### ISSUE TITLE
Issue with OpenCV

### ISSUE THREAD

**Issue by nlw0** [dorian3d/DLib#1]
Hi. When I try to build this project I get the following compilation error: 

> make
> [  3%] Building CXX object CMakeFiles/DLib.dir/src/DVision/BRIEF.cpp.o
> In file included from /home/nlw/src/DLib/src/DVision/BRIEF.cpp:13:0:
> /home/nlw/src/DLib/include/DVision/BRIEF.h:99:33: error: ‘cv’ does not name a type
>    inline void operator() (const cv::Mat &image, 
>                                  ^

It looks like cmake is picking an old version of the opencv library, where the `cv` namespace didn't exist... Do you have any idea how to deal with this by any chance?

**Comment by dorian3d** [comment]
It seems it can't find the opencv includes. If you are using opencv 3, try adding `#include <opencv2/core.hpp>` to `BRIEF.h`.

**Comment by lligen** [comment]
@dorian3d hi, i met the same problem with opencv 3, tring adding #include <opencv2/core.hpp> to BRIEF.h and xxx seems not help compiling the lib, could you please add a branch which can compile with opencv 3? so does the DBoW2~~  thank you

**Comment by houz42** [comment]
I met the same problem with opencv 2.4.12, adding `#include <opencv2/imgproc/imgproc.hpp>` to `BRIEF.cpp` finally works.

**Comment by odiseo123** [comment]
@dorian3d I am facing the same problem as @lligen while attempting to get DBoW2 running. I have managed to correct some of the errors by placing several missing headers but there are functions like the "FernClassifier" in IO.h that have been deprecated in OpenCV3. In another post (11.04.2016) you mentioned you are working in a new version. Do you have an update on that?
Thanks a lot for your time,
Andres

**Comment by dorian3d** [comment]
Should be fine in latest version.
