### ISSUE TITLE
Change in code for windows compilation

### ISSUE THREAD

**Issue by arunabhcode** [dorian3d/DLib#10]
Error in compilation in MSVC 15

Issue:

#ifdef _MSC_VER
// Microsoft Visual Studio does not ship stdint.h
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int32 uint64_t;
#else
#include <stdint.h>
#endif

Suggested Resolution:

#include<stdint.h>

as uint64_t and uint32_t are defined in MSVC 2015.

**Comment by dorian3d** [comment]
Fixed in current version.
