### ISSUE TITLE
Change in Config.cmake

### ISSUE THREAD

**Issue by arunabhcode** [dorian3d/DLib#11]
Error while compiling with MSVC 2015

**Issue:**

FIND_LIBRARY(DLib_LIBRARY DLib
  PATHS C:/Program Files (x86)/DLib/lib
)
LIST(APPEND DLib_INCLUDE_DIR
  ${DLib_INCLUDE_DIR}/../ ${DLib_INCLUDE_DIR}/../DUtils
  ${DLib_INCLUDE_DIR}/../DUtilsCV ${DLib_INCLUDE_DIR}/../DVision)

**Error Msg:**

DLib_LIBRARY not found
DLib_INCLUDE_DIR not found

**Suggested Resolution:**
FIND_LIBRARY(DLib_LIBRARY 
  NAMES DLib
  PATHS "C:/Program Files (x86)/DLib/lib"
)
LIST(APPEND DLib_INCLUDE_DIR
  "${DLib_INCLUDE_DIR}/../" "${DLib_INCLUDE_DIR}/../DUtils"
  "${DLib_INCLUDE_DIR}/../DUtilsCV" "${DLib_INCLUDE_DIR}/../DVision")

**Comment by arunabhcode** [comment]
Also it doesn't work, the only reason it worked was because I wrote my own finddlib.cmake. In any case thank you for the library :-)

**Comment by arunabhcode** [comment]
Update: It works when doing 
find_package(Dlib REQUIRED) for libraries apart from DBoW2 and DLoopDetector as strange as that might sound.

**Comment by dorian3d** [comment]
Should be fine in latest version.

**Comment by aaronkarp123** [comment]
@arunabhcode , could you expand on what you mean when you says "... for libraries apart from DBoW2"? I'm currently attempting to install DBoW2, and getting the following error (after installing Dlib in the last couple of days):

DLib library found, using it from the system
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DLib_INCLUDE_DIR
     ``used as include directory in directory /home/...

**Comment by arunabhcode** [comment]
@aaronkarp123 What I meant to say was when I do find_package(Dlib) in any other project's cmake apart from DBoW2 and DLoopDetector, it works.
