### ISSUE TITLE
legacy.hpp no such file

### ISSUE THREAD

**Issue by houz42** [dorian3d/DLib#4]
I am compiling DLib with opencv 2.4.12 on Ubuntu 14.04, failed with this cmake error:

```
[  6%] Building CXX object CMakeFiles/DLib.dir/src/DVision/FSolver.cpp.o
In file included from /home/hou/slam/dlib/include/DUtilsCV/DUtilsCV.h:47:0,
                 from /home/hou/slam/dlib/src/DVision/FSolver.cpp:17:
/home/hou/slam/dlib/include/DUtilsCV/IO.h:17:37: fatal error: opencv2/legacy/legacy.hpp: No such file or directory
 #include <opencv2/legacy/legacy.hpp>
```

I am not familiar with these compiling things, could anyone be help?

**Comment by dorian3d** [comment]
The latest OpenCV version moved some headers. You can comment out that line, but probably some other errors will appear. I'll update the code to make it compatible with the new OpenCV shortly.

**Comment by houz42** [comment]
thank you for your advance and your great work.
